version: '3.3'
services:
  mongo:
    image: mongo
    container_name: auth_db
    volumes:
      - ./mongo-data:/data/db

  auth_server:
    build: ./server
    container_name: auth_server
    volumes:
      - ./server/app.js:/server/app.js
      - ./server/config/:/server/config
      - ./server/source/:/server/source
      - ./server/logs/:/server/logs
    command: /bin/sh -c "npm run ${MODE}"
    ports:
      - '3030:3030'

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - '80:80'
    depends_on:
      - auth_server
