version: '3.3'
services:
  mongo:
    image: mongo
    container_name: auth_db
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '127.0.0.1:27017:27017'

  auth_server:
    build: ./
    container_name: auth_server
    volumes:
      - ./app.js:/server/app.js
      - ./config/:/server/config
      - ./source/:/server/source
    ports:
      - '${PORT}:${PORT}'
    command: /bin/sh -c "npm run ${MODE}"
    depends_on:
      - mongo
